### ISSUE TITLE
short-cycle: check for presence of media playlists in the master

### ISSUE THREAD

**Issue by iameli** [livepeer/stream-monitor#6]
So we had a region down for a number of hours last night - specifically, RTMP ingest worked, but the appropriate playback routes weren't getting added to Consul. So any time playback was attempted, an HTTP 200 was returned along with this playlist:

```
▶ curl https://region-cdn.livepeer.com/hls/doesnotexist/index.m3u8
#EXTM3U
#EXT-X-ERROR: Stream open failed
#EXT-X-ENDLIST
```

The short cycle streams apparently did not treat this as an error condition — I assume it was determining that all 0 of the 0 media playlists were returning data correctly or some such. This should throw an error.

**Comment by thedeeno** [comment]
I'll update the short-cycle to check for this and send a page.

**Comment by wohlner** [comment]
Is this done?

**Comment by thedeeno** [comment]
@wohlner yup! Sorry for not closing right away.
